### ISSUE TITLE
Unnecessary menu structure?

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#18]
We probably don’t need a hamburger menu if it only has 2-3 items. We can display them directly in the header like in the original design.

![](https://i.imgur.com/6Zb7bpa.jpg)

**Comment by quiet-ocean** [comment]
@tldstyl3 We should go back to origin design?

**Comment by quiet-ocean** [comment]
@tldstyl3 I hope to invite you to our slack workspace too. I think it would help to improve the syncronizing our work. Could you let me know your email address?
