### ISSUE TITLE
Google Play / App Store buttons not working

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#20]

**Comment by quiet-ocean** [comment]
What urls should be linked to those buttons?

**Comment by tldstyl3** [comment]
You can get the live URLs from the original website - https://nurture.games/

Sharing here as well:

App Store - https://apps.apple.com/app/id1663944460
Google Play - https://play.google.com/store/apps/details?id=com.nurturegames.counttruck

**Comment by quiet-ocean** [comment]
@tldstyl3 Okay, your email?
