### ISSUE TITLE
Portrait layout looks weird

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#21]
The 3-piece grid feels super weird in portrait.

![](https://i.imgur.com/H6GGxxv.png)

![](https://i.imgur.com/kvq45S2.png)

**Comment by quiet-ocean** [comment]
@tldstyl3  You are checking on old version. Please visit /index14 as default.

**Comment by tldstyl3** [comment]
OK, will look at index14 moving forward. Miles agency needs to go and we probably need to align the button images to the center.

![](https://i.imgur.com/1M0T3vR.jpg)

**Comment by quiet-ocean** [comment]
@tldstyl3 okay, could you let me know your email address? it will be better if we chat on slack. Erdi is already there.

**Comment by quiet-ocean** [comment]
@tldstyl3 I will invite you to our slack channle with Erdi.

**Comment by tldstyl3** [comment]
I can confirm that Miles Agency is gone and the buttons are centered. The weird 3-grid array is still there, though?

![IMG_2206](https://github.com/xarion/expert-octo-adventure/assets/132054625/392f7154-43bb-421b-8dc2-eefcca7029bb)
![IMG_2207](https://github.com/xarion/expert-octo-adventure/assets/132054625/1f66765c-d89c-44ec-bc00-1485ff3296d1)

**Comment by xarion** [comment]
Let's switch those to the ones we used for the features above.
