### ISSUE TITLE
Writing effect shouldn’t move active buttons

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#24]
![ezgif com-crop](https://github.com/xarion/expert-octo-adventure/assets/132054625/f06ee7a1-7228-4ffb-911e-db8666820c06)

**Comment by quiet-ocean** [comment]
@tldstyl3 okay.

**Comment by tldstyl3** [comment]
Button movement is fixed! Can we somehow anchor the rest of the content below so it doesn’t move as much when you’re trying to read?

![ezgif com-optimize 2](https://github.com/xarion/expert-octo-adventure/assets/132054625/0a8d1cbc-e695-4133-a9a1-5793a13a2c45)
