### ISSUE TITLE
“Let’s talk” chat button not working

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#26]
And it’s also visible only in Landscape?

![IMG_2204](https://github.com/xarion/expert-octo-adventure/assets/132054625/1c917bad-fae3-4ea9-aa89-e90c7e272f7f)
![IMG_2205](https://github.com/xarion/expert-octo-adventure/assets/132054625/00e8a28a-73d6-4bc5-8825-2146e4a21562)

**Comment by quiet-ocean** [comment]
I checked the chat button again. It works properly but a bit late because it takes long time to load resources. check it a bit later after visit the site.

**Comment by tldstyl3** [comment]
Hm, that’s not ideal. It should work all of the time or we should just hide it if it’s a problem.

@xarion Any thoughts?

**Comment by xarion** [comment]
Let's remove it for now

**Comment by quiet-ocean** [comment]
Removed that button
