### ISSUE TITLE
Update Favicon + page title

### ISSUE THREAD

**Issue by tldstyl3** [xarion/expert-octo-adventure#31]
Here’s the favicon we have on the original website:
![image](https://github.com/xarion/expert-octo-adventure/assets/132054625/f8e8495e-5a67-4c53-b507-58ef6a08a837)

This is what you currently see if you have the Blog section opened:
<img width="122" alt="image" src="https://github.com/xarion/expert-octo-adventure/assets/132054625/9ebbdf22-3251-4b6d-be52-770b835128b7">

**Comment by quiet-ocean** [comment]
So what is the proper favicon? please share with resource.

**Comment by tldstyl3** [comment]
It’s attached above.

![](https://user-images.githubusercontent.com/132054625/276177785-f8e8495e-5a67-4c53-b507-58ef6a08a837.png)

**Comment by quiet-ocean** [comment]
What is proper page title?
